name: mitm-webp-compress-proxy
services:
    mitm-webp-compress-proxy:
        stdin_open: true
        tty: true
        restart: always
        volumes:
            - ~/.mitmproxy:/home/mitmproxy/.mitmproxy
            - ./:/home/mitmproxy/files
        environment:
            - MITM_USER=myusername
            - MITM_PASS=mysupersafepass
        ports:
            - 3126:3126
        image: mitm-webp-compress-proxy
